// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFtd10NU_Alx0Y1xZE8W6OjdfddPPCP8',
    appId: '1:959320965645:web:5f4d437a5f68b10680cb44',
    messagingSenderId: '959320965645',
    projectId: 'loginpassowrd-1fca9',
    authDomain: 'loginpassowrd-1fca9.firebaseapp.com',
    storageBucket: 'loginpassowrd-1fca9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx8uYVOrc2-NuTJ9p6BdCBlpKCsv5kZI4',
    appId: '1:959320965645:android:eee747dc17cf751380cb44',
    messagingSenderId: '959320965645',
    projectId: 'loginpassowrd-1fca9',
    storageBucket: 'loginpassowrd-1fca9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARn0wBlDZrHmumonU_9AmIlojVUeAFqZE',
    appId: '1:959320965645:ios:9917405b0bd8f30180cb44',
    messagingSenderId: '959320965645',
    projectId: 'loginpassowrd-1fca9',
    storageBucket: 'loginpassowrd-1fca9.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARn0wBlDZrHmumonU_9AmIlojVUeAFqZE',
    appId: '1:959320965645:ios:9917405b0bd8f30180cb44',
    messagingSenderId: '959320965645',
    projectId: 'loginpassowrd-1fca9',
    storageBucket: 'loginpassowrd-1fca9.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJFtd10NU_Alx0Y1xZE8W6OjdfddPPCP8',
    appId: '1:959320965645:web:7d8234305a304ff480cb44',
    messagingSenderId: '959320965645',
    projectId: 'loginpassowrd-1fca9',
    authDomain: 'loginpassowrd-1fca9.firebaseapp.com',
    storageBucket: 'loginpassowrd-1fca9.firebasestorage.app',
  );
}
